# Starter pipeline
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Sritesting'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Run your generic shell script
- task: Bash@3
  inputs:
    filePath: './runscript.sh'

# Publish the JUnit report from Testsigma
- task: PublishTestResults@2
  displayName: 'Publish Testsigma Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'          # Correct capitalization
    testResultsFiles: '/Users/sridhar/Documents/new_azure/vsts-agent-osx-arm64-4.254.0/_work/1/s/junit-report.xml'
