trigger:
- master

pool: Testingwin

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- task: Bash@3 
 inputs:    
filePath: './myscriptwin.bat'

- task: VSTest@2
  inputs:
    testSelector: 'testPlan'
    testPlan: '1'
    testSuite: '2'
    testConfiguration: '1' 

# Publish test results
- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'  # Correct format for JUnit
    testResultsFiles: '**/junit-report-*.xml'  # Correct file path syntax
    failTaskOnFailedTests: true
