trigger:
- master

pool: 
  name: 'Testingwin'  # Make sure to use the correct agent pool name

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

# Use script task for running .bat files on Windows
- script: .\myscriptwin.bat
  displayName: 'Run a batch script'

- script: |
    dotnet test --filter "TestPlanId=1" --configuration Release
    displayName: 'Run .NET Tests'

# Publish test results
- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'  # Correct format for JUnit
    testResultsFiles: '**/junit-report-*.xml'  # Correct file path syntax
    failTaskOnFailedTests: true
