trigger:
- master

pool:
  name: testing

steps:  # Add 'steps' to define the sequence of tasks

# Run a shell script
- task: Bash@3
  inputs:
    filePath: './myscriptci.sh'   

# Publish test results
- task: PublishTestResults@2
  displayName: 'Publish Testsigma test results'
  inputs:
    testResultsFormat: 'JUnit'  # Fix the format, must be 'JUnit' (case-sensitive)
    testResultsFiles: '**/junit-report-*.xml'
    mergeTestResults: true
    testPlan: '1'
    testSuite: '1'
