trigger:
- master

pool: 
  name: 'testing'
  
- task: Bash@3 
 inputs:    
filePath: './myscriptci.sh' //Generic Shell Script file

//Settings
- task: PublishTestResults@2  
displayName: 'publish testsigma test results'  
inputs:    
testResultsFormat: 'Junit'// Test Result Format   
testResultsFiles: '**/junit-report-*.xml' 
