trigger:
- master

pool:
  vmImage: 'windows-latest'  # Use an agent with .NET SDK support

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Specify the desired SDK version (e.g., 6.0.100)
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: .\myscriptwin.bat
  displayName: 'Run a batch script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'  # Adjust the path to your project files

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'  # Adjust this path to your test project files
    arguments: '--configuration Release'

- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'
    testResultsFiles: './junit-report.xml'
    failTaskOnFailedTests: true
