trigger:
- master

pool: 
  name: 'Testingwin'  # Make sure to use the correct agent pool name

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

# Use script task for running .bat files on Windows
- script: .\myscriptwin.bat
  displayName: 'Run a batch script'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Specify the desired SDK version
    installationPath: $(Agent.ToolsDirectory)/dotnet    

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration Release'  

# Publish test results
- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'  # Correct format for JUnit
    testResultsFiles: './junit-report.xml'  # Correct file path syntax
    failTaskOnFailedTests: true
