trigger:
- master

pool: 'sridhar'

steps:
- script: echo "Hello, world!"  
  displayName: 'Run a one-line script'

# Run a generic shell script file
- task: Bash@3 
  inputs:    
    filePath: './myscriptci.sh'

# Publish test results
- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'  # Correct format for JUnit
    testResultsFiles: '**/junit-report.xml'  # Correct file path syntax
