trigger:
- master

pool:  'testing'


steps:
- script: echo "Hello, world!"  
  displayName: 'Run a one-line script'

# Run a generic shell script file
- task: Bash@3 
  inputs:    
    filePath: './myscriptci.sh'

- task: RunTests@2
  displayName: 'Run Tests from Test Plan'
  inputs:
    testSelector: 'testPlan'
    testPlan: '4'        # Replace with the actual Test Plan ID
    testSuite: '6'      # Replace with the actual Test Suite ID
    testConfiguration: '1'  # Replace with the actual Test Configuration ID    

# Publish test results
- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'  # Correct format for JUnit
    testResultsFiles: '**/junit-report-*.xml'  # Correct file path syntax
    failTaskOnFailedTests: true
