trigger:
- master

pool: 
  name: 'testing'

steps:  # Add 'steps' to define the sequence of tasks

# Run a shell script
- task: Bash@3
  inputs:
    filePath: './myscriptci.sh'

# Publish test results
- task: PublishTestResults@2
  displayName: 'Publish Testsigma test results'
  inputs:
    testResultsFormat: 'JUnit'  # Fix the format, must be 'JUnit' (case-sensitive)
    testResultsFiles: '**/junit-report-*.xml'

# Use the Azure DevOps CLI or a custom script to link the test results to Test Plans or Suites
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Using Azure DevOps REST API to update the Test Plan with test results
      curl -X POST \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $(System.AccessToken)" \
      https://dev.azure.com/$(System.TeamProject)/_apis/testplan/Plans/1/suites/2/results?api-version=7.0 \
      --data '{
        "testPlan": {
          "id": 1
        },
        "testSuite": {
          "id": 1
        },
        "results": $(System.DefaultWorkingDirectory)/TestResults/**/junit-report-*.xml
      }'
  displayName: 'Link Test Results to Test Plan and Test Suite'
