trigger:
- master

pool: 'testing'

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

# Run a generic shell script file
- task: Bash@3
  inputs:    
    filePath: './myscriptci.sh' 

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'  # Adjust the path to your test project if necessary
    arguments: '--configuration Release --logger "trx;LogFileName=test-results.trx"'
    

# Publish test results
- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'  # Correct format for JUnit
    testResultsFiles: '**/junit-report-*.xml'  # Correct file path syntax
    failTaskOnFailedTests: true
