trigger:
- master

pool: 
  name: 'Testingwin'  # Make sure to use the correct agent pool name

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

# Use script task for running .bat files on Windows
- script: .\myscriptwin.bat
  displayName: 'Run a batch script'

- task: VSTest@2
  inputs:
    vsTestVersion: '17.0'
    testSelector: 'testPlan'
    testPlan: '1'
    testSuite: '2'
    testConfiguration: '1' 

# Publish test results
- task: PublishTestResults@2  
  displayName: 'Publish Testsigma test results'  
  inputs:    
    testResultsFormat: 'JUnit'  # Correct format for JUnit
    testResultsFiles: '**/junit-report-*.xml'  # Correct file path syntax
    failTaskOnFailedTests: true
